version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: volleyball-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: volleyball_rpg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: acessoabasededados
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: volleyball-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass acessoaocache
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "acessoaocache", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: Redis Commander (Web UI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: volleyball-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:volleyball-redis:6379:0:acessoaocache
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - tools

  # Optional: pgAdmin (Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: volleyball-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@volleyball.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgladmin
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
